application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musicshop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicshop/urls.py
from django.urls import path
from .views import BaseView, \
    ArtistDetailView, \
    AlbumDetailView, \
    RegistrationView, \
    LoginView, \
    AccountView, \
    CartView, \
    AddToCartView, \
    DeleteFromCartView, \
    ChangeQTYView, \
    AddToWishlist, ClearNotificationsView, \
    RemoveFromWishListView, \
    CheckoutView, MakeOrderView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('', BaseView.as_view(), name='base'),
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('account/', AccountView.as_view(), name='account'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make-order'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('add-to-wishlist/<int:album_id>/', AddToWishlist.as_view(), name='add_to_wishlist'),
    path('remove-from-wishlist/<int:album_id>/', RemoveFromWishListView.as_view(), name='remove_from_wishlist'),
    path('clear-notifications/', ClearNotificationsView.as_view(), name="clear_notifications"),
    path('<str:artist_slug>/', ArtistDetailView.as_view(), name="artist_detail"),
    path('<str:artist_slug>/<str:album_slug>/', AlbumDetailView.as_view(), name="album_detail"),
]

musicshop/models.py
from calendar import monthrange
from datetime import datetime

from django.db import models, connection
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.utils import timezone
import operator
from django.db.models.signals import post_save, pre_save
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.safestring import mark_safe

from utils import upload_function


class MediaType(models.Model):
    """Медианоситель"""

    name = models.CharField(max_length=100, verbose_name="Название медиа носителья")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Медианоситель"
        verbose_name_plural = "Медианосители"


class Member(models.Model):
    """Музыкант"""

    name = models.CharField(max_length=255, verbose_name="Имя музыканта")
    slug = models.SlugField()
    image = models.ImageField(upload_to=upload_function, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Музыкант"
        verbose_name_plural = "Музыканты"


class Genre(models.Model):
    """Музыкальный жанр"""

    name = models.CharField(max_length=50, verbose_name="Название жанра")
    slug = models.SlugField()  # /genre/pop/

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Artist(models.Model):
    """Исполнитель"""

    name = models.CharField(max_length=255, verbose_name="Исполнитель/группа")
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    members = models.ManyToManyField(Member, verbose_name="Участник",
                                     related_name="artist")  # Погуглить что это за связь
    image_gallery = GenericRelation('imagegallery')
    slug = models.SlugField()
    image = models.ImageField(upload_to=upload_function, blank=True, null=True)

    def __str__(self):
        return f"{self.name} | {self.genre.name}"

    def get_absolute_url(self):
        return reverse('artist_detail', kwargs={"artist_slug": self.slug})

    class Meta:
        verbose_name = "Исполнитель"
        verbose_name_plural = "Исполнители"


class AlbumManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset()

    def get_month_bestseller(self):
        today = datetime.today()
        year, month = today.year, today.month
        first_day = datetime(year, month, 1)
        last_day = datetime(year, month, monthrange(year, month)[1])
        query = f"""
            SELECT shop_product.id as product_id, SUM(distinct shop_cart_product.qty) as total_qty
            FROM musicshop_order as shop_order
            JOIN musicshop_cart as shop_cart on shop_order.cart_id = shop_cart.id
            JOIN musicshop_cartproduct as shop_cart_product on shop_cart.id = shop_cart_product.card_id
            JOIN musicshop_album as shop_product on shop_cart_product.object_id=shop_product.id
            WHERE shop_order.order_date >= '{first_day}' and shop_order.order_date <= '{last_day}'
            GROUP BY product_id
            ORDER BY total_qty DESC
            LIMIT 1
        """
        with connection.cursor() as cursor:
            cursor.execute(query)
            row = cursor.fetchone()
        if row:
            product_id, qty = row
            album = Album.objects.get(pk=product_id)
            return album, qty
        return None, None


class Album(models.Model):
    """Альбом исполнителя"""

    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, verbose_name="Исполнитель")
    name = models.CharField(max_length=255, verbose_name="Название альбома")
    media_type = models.ForeignKey(MediaType, verbose_name="Носитель", on_delete=models.CASCADE)
    songs_list = models.TextField(verbose_name="Трэклист")
    release_date = models.DateField(verbose_name="Дата релиза")
    slug = models.SlugField()
    description = models.TextField(verbose_name="Описание", default='Описание появится позже')
    stock = models.IntegerField(default=1, verbose_name="Наличие на складе")
    out_of_stock = models.BooleanField(default=False, verbose_name="Нет в наличии")
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")
    offer_of_the_week = models.BooleanField(default=False, verbose_name='Предложение недели?')
    image = models.ImageField(upload_to=upload_function)
    objects = AlbumManager()

    def __str__(self):
        return f'{self.id} | {self.artist.name} | {self.name}'

    @property
    def ct_model(self):
        return self._meta.model_name

    def get_absolute_url(self):
        return reverse('album_detail', kwargs={'artist_slug': self.artist.slug, "album_slug": self.slug})

    class Meta:
        verbose_name = "Альбом"
        verbose_name_plural = "Альбомы"


class CartProduct(models.Model):
    """Продукт корзины"""

    MODEL_CARTPRODUCT_DISPLAY_NAME_MAP = {
        'Album': {"is_constructable": True, 'fields': ['name', 'artist.name'], 'separator': ' - '}
    }

    user = models.ForeignKey('Customer', verbose_name="Покупатель", on_delete=models.CASCADE)
    card = models.ForeignKey('Cart', verbose_name="Корзина", on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая цена")

    def __str__(self):
        return f'Продукт: {self.content_object.name} (для корзины)'

    @property
    def display_name(self):
        model_fields = self.MODEL_CARTPRODUCT_DISPLAY_NAME_MAP.get(
            self.content_object.__class__._meta.model_name.capitalize())
        if model_fields and model_fields['is_constructable']:
            display_name = model_fields['separator'].join(
                [operator.attrgetter(field)(self.content_object) for field in model_fields['fields']]
            )
            return display_name
        if model_fields and not model_fields['is_constructable']:
            display_name = operator.attrgetter(model_fields['field'])(self.content_object)
            return display_name
        return self.content_object

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Продукт корзины"
        verbose_name_plural = "Продукты корзины"


class Cart(models.Model):
    """Корзина"""

    owner = models.ForeignKey('Customer', verbose_name="Покупатель", on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart',
                                      verbose_name="Продукты для корзины")
    total_products = models.IntegerField(default=0, verbose_name="Общее кол-во товара")
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая цена",
                                      null=True, blank=True)
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def products_in_cart(self):
        return [c.content_object for c in self.products.all()]

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"


class Order(models.Model):
    """Заказ пользователя"""

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = "in_progress"
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = "self"
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, "Новый заказ"),
        (STATUS_IN_PROGRESS, "Заказ в обработке"),
        (STATUS_READY, "Заказ готов"),
        (STATUS_COMPLETED, "Заказ получен покупателем")
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, "Самовывоз"),
        (BUYING_TYPE_DELIVERY, "Доставка")
    )

    customer = models.ForeignKey('Customer', verbose_name="Покупатель", related_name="orders",
                                 on_delete=models.CASCADE)
    first_name = models.CharField(verbose_name="Имя", max_length=255)
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    cart = models.ForeignKey(Cart, null=True, blank=True, verbose_name="Корзина", on_delete=models.CASCADE)
    address = models.CharField(max_length=1024, verbose_name="Адрес", null=True, blank=True)
    status = models.CharField(max_length=100, verbose_name="Статус заказа", choices=STATUS_CHOICES, default=STATUS_NEW)
    buying_type = models.CharField(max_length=100, verbose_name='Тип заказа', choices=BUYING_TYPE_CHOICES)
    comment = models.TextField(verbose_name="Комментарий к заказу", blank=True, null=True)
    created_at = models.DateField(verbose_name="Дата создания заказа", auto_now=True)
    order_date = models.DateField(verbose_name="Дата получения заказа", default=timezone.now())

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class Customer(models.Model):
    """Покупатель"""

    user = models.OneToOneField(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True, verbose_name="Активный?")
    customer_order = models.ManyToManyField(Order, blank=True, related_name="related_customer",
                                            verbose_name="Заказы покупателя")
    wishlist = models.ManyToManyField(Album, blank=True, verbose_name="Список ожидаемого")
    phone = models.CharField(max_length=20, verbose_name="Номер телефона")

musicshop/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Order

User = get_user_model()  # Более правильный подход для получения модели пользователя


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = "Дата получения заказа"

    order_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))

    class Meta:
        model = Order
        fields = ("first_name", "last_name", "phone", "address", "buying_type",
                  "order_date", "comment")


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        user = User.objects.filter(username=username).first()
        if not user:
            raise forms.ValidationError(f"Пользователь с логином {username} не найден в системе")
        if not user.check_password(password):
            raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)  # required - необязательно
    address = forms.CharField(required=False)  # required - необязательно
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Почта'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['net', 'xyz']:
            raise forms.ValidationError(f"Регистрация для домена {domain} невозможна")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Данный почтоый адрес уже зарегестрирован")
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f"Имя {username} занято. Попробуйте другое.")
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError("Пароли не совпадают")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']

musicshop/templates/account.html
{% extends 'base.html' %}

{% block content %}

    <h4 class="text-center">Личный кабинет</h4>
    <hr>
        <div class="row">
          <div class="col-4">
            <div class="list-group" id="list-tab" role="tablist">
              <a class="list-group-item list-group-item-action active" id="list-orders-list" data-bs-toggle="list" href="#list-orders" role="tab" aria-controls="list-orders">Заказы</a>
              <a class="list-group-item list-group-item-action" id="list-wishlist-list" data-bs-toggle="list" href="#list-wishlist" role="tab" aria-controls="list-wishlist">Лист ожидания</a>
            </div>
          </div>
          <div class="col-8">
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="list-orders" role="tabpanel" aria-labelledby="list-orders-list">
                  <table class="table">
                      <thead>
                            <tr>
                                <th scope="col">Номер заказа</th>
                                <th scope="col">Статус</th>
                                <th scope="col">Сумма</th>
                                <th scope="col">Детали</th>
                            </tr>
                      </thead>
                    <tbody>
                        {% for order in customer.orders.all %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.get_status_display }}</td>
                                <td>{{ order.cart.final_price }} руб.</td>
                                <td><button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#orderDetails-{{ order.id }}">Детали заказа</button></td>
                            <div class="modal fade" id="orderDetails-{{ order.id }}" tabindex="-1"
                                 aria-labelledby="orderDetailsLabel-{{ order.id }}" aria-hidden="true">
                                <div class="modal-dialog modal-xl">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title text-center" id="orderDetailsLabel-{{ order.id }}">
                                                Информация о заказе #{{ order.id }}
                                            </h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="row">
                                                <div class="col-md-3 text-center mb-2">
                                                    <strong>Исполнитель/альбом</strong>
                                                </div>
                                                <div class="col-md-3 text-center mb-2">
                                                    <strong>Изображение</strong>
                                                </div>
                                                 <div class="col-md-3 text-center mb-2">
                                                    <strong>Кол-во</strong>
                                                </div>
                                                <div class="col-md-3 text-center mb-2">
                                                    <strong>Общая цена</strong>
                                                </div>
                                            <hr>
                                            {% for item in order.cart.products.all %}
                                                <div class="col-md-3 mb-3 text-center">
                                                    <strong>
                                                        <a href="{{ item.content_object.artist.get_absolute_url }}"
                                                           class="text-decoration-none">
                                                            {{ item.content_object.artist.name }}
                                                        </a> - <a href="{{ item.content_object.get_absolute_url }}"
                                                                  class="text-decoration-none">
                                                        {{ item.content_object.name }}
                                                    </a>
                                                    </strong>

                                                </div>
                                                <div class="col-md-3 mb-3 text-center">
                                                    <img src="{{ item.content_object.image.url }}" class="img-fluid">
                                                </div>
                                                <div class="col-md-3 mb-3 text-center">
                                                    {{ item.qty }} шт.
                                                </div>
                                                <div class="col-md-3 mb-3 text-center">
                                                    {{ item.final_price }} руб.
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                            Закрыть
                                        </button>
                                    </div>
                                </div>
                            </div>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
              </div>
              <div class="tab-pane fade" id="list-wishlist" role="tabpanel" aria-labelledby="list-wishlist-list">
                  <div class="row">
                      {% for album in customer.wishlist.all %}
                          <div class="card col-md-4 p-0 mb-3 mt-3">
                            <img src="{{ album.image.url }}" class="card-img-top">
                            <div class="card-body text-center">
                                <h5 class="card-title"><a href="{{ album.artist.get_absolute_url }}" class="text-decoration-none">
                                    {{ album.artist.name }}
                                </a></h5>
                                <h5 class="card-title"><a href="{{ album.get_absolute_url }}" class="text-decoration-none">
                                    {{ album.name }}
                                </a></h5>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    Носитель: <strong>{{ album.media_type.name }}</strong>
                                </li>
                                <li class="list-group-item">
                                    Дата релиза: <strong>{{ album.release_date|date:"d-m-Y" }}</strong>
                                </li>
                                <li class="list-group-item">
                                    Жанр: <strong class="badge bg-dark">{{ album.artist.genre.name }}</strong>
                                </li>
                                <li class="list-group-item">
                                    Наличие: {% if album.stock %}<strong class="badge bg-success">
                                    Есть в наличии</strong>{% else %}
                                    <strong class="badge bg-danger">Нет в наличии</strong>{% endif %}
                                </li>
                            </ul>
                            <div class="card-body text-center">
                                <a href="{% url 'remove_from_wishlist' album_id=album.id %}"
                                   class="btn btn-danger">Удалить из ожидаемого <i class="fas fa-star"></i></a>
                            </div>
                          </div>
                      {% endfor %}
                  </div>
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

musicshop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'base' %}">MusicShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'base' %}">Главная</a>
        </li>
          {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Авторизация</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration' %}">Регистрация</a>
            </li>
          {% else %}
              <li class="nav-item">
              <a class="nav-link" href="{% url 'account' %}">Личный кабинет</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Уведомления <i class="fas fa-bell"></i>
                    <span class="badge bg-{% if notifications.count %}danger{% else %}secondary{% endif %}">
                        {{ notifications.count }}
                    </span>
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if notifications %}
                            {% for n in notifications %}
                                <li><span class="dropdown-item">{{ n.text|safe }}</span></li>
                            {% endfor %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a href="{% url 'clear_notifications' %}" class="dropdown-item">Пометить все как прочитанное</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="#">Нет новых уведомлений</a></li>
                        {% endif %}
                    </ul>
              </li>
          {% endif %}
      </ul>
    {% if request.user.is_authenticated %}
      <ul class="navbar-nav" >
          <li class="nav-item"><a href="{% url 'cart' %}" class="nav-link"><i class="fas fa-shopping-cart"></i> <span class="badge bg-danger">{{ cart.products.count }}</span></a></li>
      </ul>
    {% endif %}
    </div>
  </div>
</nav>

<div class="container">
    {% block content %}
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <h4 class="text-center">Хит продаж текущего месяца</h4>
                    <a href="{{ month_bestseller.get_absolute_url }}">{{ month_bestseller.name }}</a>
                </div>
                <div class="col-md-4"></div>
            </div>
            <div class="row">
                {% for album in albums %}
                    <div class="card col-md-3 p-0 mb-3 mt-3">
                        <img src="{{ album.image.url }}" class="card-img-top" alt="Произошла ошибка при загрузке">
                        <div class="card-body text-center">
                            <h5 class="card-title"><a href="{{ album.artist.get_absolute_url }}" class="text-decoration-none">
                                {{ album.artist.name }}
                            </a></h5>
                            <h5 class="card-title"><a href="{{ album.get_absolute_url }}" class="text-decoration-none">
                                {{ album.name }}
                            </a></h5>
                        </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Носитель: <strong>{{ album.media_type.name }}</strong></li>
                        <li class="list-group-item">Дата релиза: <strong>{{ album.release_date|date:"d-m-Y" }}</strong></li>
                        <li class="list-group-item">Жанр: <strong>{{ album.artist.genre.name }}</strong></li>
                        <li class="list-group-item">
                            Наличие: {% if album.stock %}<strong class="badge bg-success">
                            Есть в наличии - {{ album.stock }} шт.
                        </strong>{% else %}
                            <strong class="badge bg-danger">Нет в наличии</strong>
                        {% endif %}
                        </li>
                    </ul>
                        <div class="card-body text-center">

                        {% if request.user.is_authenticated %}

                            {% if album.stock %}
                                {% if album not in cart.products_in_cart %}
                                    <a href="{% url 'add_to_cart' ct_model=album.ct_model slug=album.slug %}">
                                        <button class="btn btn-primary">
                                            Добавить в корзину
                                        </button>
                                    </a>
                                {% else %}
                                    <a href="#" class="btn btn-default" disabled="">Добавлен в корзину</a>
                                {% endif %}
                            {% else %}
                                    {% if album not in request.user.customer.wishlist.all %}
                                        <a href="{% url 'add_to_wishlist' album_id=album.id %}" class="btn btn-warning">
                                            Добавить в ожидаемое
                                        </a>
                                    {% else %}
                                        <a href="#" class="btn btn-default" disabled="">Добавлен в ожидаемое</a>
                                    {% endif %}
                            {% endif %}
                        {% else %}
                            <a href="#" class="btn btn-default" disabled="">
                                Авторизуйтесь или зарегистрируйтесь, только авторизованные пользователи
                                могут осуществлять заказы
                            </a>
                        {% endif %}
                    </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    {% endblock content %}
</div>
</body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</html>